[app]
overall = { bg = "#f7f7f8" }

[mgr]
cwd = { fg = "#287f76" }

find_keyword = { fg = "#8b6b22", italic = true }
find_position = { fg = "#b84f83", bg = "reset", italic = true }

marker_copied = { fg = "#398460", bg = "#398460" }
marker_cut = { fg = "#c94f55", bg = "#c94f55" }
marker_marked = { fg = "#287f76", bg = "#287f76" }
marker_selected = { fg = "#347aa5", bg = "#347aa5" }

count_copied = { fg = "#f7f7f8", bg = "#398460" }
count_cut = { fg = "#f7f7f8", bg = "#c94f55" }
count_selected = { fg = "#f7f7f8", bg = "#347aa5" }

border_symbol = "│"
border_style = { fg = "#89898e" }

syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

[tabs]
active = { fg = "#f7f7f8", bg = "#303033", bold = true }
inactive = { fg = "#303033", bg = "#e3e3e5" }

[mode]
normal_main = { fg = "#f7f7f8", bg = "#347aa5", bold = true }
normal_alt = { fg = "#347aa5", bg = "#eeeeef" }

select_main = { fg = "#f7f7f8", bg = "#398460", bold = true }
select_alt = { fg = "#398460", bg = "#eeeeef" }

unset_main = { fg = "#f7f7f8", bg = "#c85d61", bold = true }
unset_alt = { fg = "#c85d61", bg = "#eeeeef" }

[indicator]
parent = { fg = "#f7f7f8", bg = "#303033" }
current = { fg = "#f7f7f8", bg = "#347aa5" }
preview = { fg = "#f7f7f8", bg = "#303033" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#398460", bg = "#e3e3e5" }
progress_error = { fg = "#8b6b22", bg = "#c94f55" }

perm_type = { fg = "#347aa5" }
perm_read = { fg = "#8b6b22" }
perm_write = { fg = "#c94f55" }
perm_exec = { fg = "#398460" }
perm_sep = { fg = "#89898e" }

[input]
border = { fg = "#347aa5" }
title = {}
value = {}
selected = { reversed = true }

[pick]
border = { fg = "#347aa5" }
active = { fg = "#b84f83" }
inactive = {}

[confirm]
border = { fg = "#347aa5" }
title = { fg = "#347aa5" }
body = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}

[cmp]
border = { fg = "#347aa5" }

[tasks]
border = { fg = "#347aa5" }
title = {}
hovered = { fg = "#b84f83", bold = true }

[which]
mask = { bg = "#eeeeef" }
cand = { fg = "#287f76" }
rest = { fg = "#737378" }
desc = { fg = "#b84f83" }
separator = "  "
separator_style = { fg = "#d8d8da" }

[help]
on = { fg = "#287f76" }
run = { fg = "#b84f83" }
desc = { fg = "#737378" }
hovered = { bg = "#d8d8da", bold = true }
footer = { fg = "#303033", bg = "#e3e3e5" }

[notify]
title_info = { fg = "#287f76" }
title_warn = { fg = "#8b6b22" }
title_error = { fg = "#c94f55" }

[filetype]
rules = [
  # Media
  { mime = "image/*", fg = "#8b6b22" },
  { mime = "{audio,video}/*", fg = "#b84f83" },

  # Archives
  {
    mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}",
    fg = "#c94f55"
  },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#367fa3" },

  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "#e3e3e5" },

  # Special file
  { url = "*", is = "orphan", bg = "#c94f55" },
  { url = "*", is = "exec", fg = "#398460" },

  # Dummy file
  { url = "*", is = "dummy", bg = "#c94f55" },
  { url = "*/", is = "dummy", bg = "#c94f55" },

  # Fallback
  { url = "*/", fg = "#347aa5" },
]

[spot]
border = { fg = "#347aa5" }
title = { fg = "#347aa5" }
tbl_cell = { fg = "#347aa5", reversed = true }
tbl_col = { bold = true }

[icon]
dirs = [
  { name = ".config", text = "", fg = "#347aa5" },
  { name = ".git", text = "", fg = "#347aa5" },
  { name = ".github", text = "", fg = "#347aa5" },
  { name = ".npm", text = "", fg = "#347aa5" },
  { name = "Desktop", text = "", fg = "#347aa5" },
  { name = "Development", text = "", fg = "#347aa5" },
  { name = "Documents", text = "", fg = "#347aa5" },
  { name = "Downloads", text = "", fg = "#347aa5" },
  { name = "Library", text = "", fg = "#347aa5" },
  { name = "Movies", text = "", fg = "#347aa5" },
  { name = "Music", text = "", fg = "#347aa5" },
  { name = "Pictures", text = "", fg = "#347aa5" },
  { name = "Public", text = "", fg = "#347aa5" },
  { name = "Videos", text = "", fg = "#347aa5" },
]
conds = [
  # Special files
  { if = "orphan", text = "", fg = "#303033" },
  { if = "link", text = "", fg = "#606064" },
  { if = "block", text = "", fg = "#8b6b22" },
  { if = "char", text = "", fg = "#8b6b22" },
  { if = "fifo", text = "", fg = "#8b6b22" },
  { if = "sock", text = "", fg = "#8b6b22" },
  { if = "sticky", text = "", fg = "#8b6b22" },
  { if = "dummy", text = "", fg = "#c94f55" },

  # Fallback
  { if = "dir", text = "", fg = "#347aa5" },
  { if = "exec", text = "", fg = "#398460" },
  { if = "!dir", text = "", fg = "#303033" },
]
