set -g @catppuccin_rosewater '#ffcdc7',
set -g @catppuccin_flamingo  '#ffafaf',
set -g @catppuccin_pink      '#e99cba',
set -g @catppuccin_mauve     '#b5ccff',
set -g @catppuccin_red       '#f88d8e',
set -g @catppuccin_maroon    '#f1a290',
set -g @catppuccin_peach     '#fbc19d',
set -g @catppuccin_yellow    '#e9cc9c',
set -g @catppuccin_green     '#7fc7a4',
set -g @catppuccin_teal      '#7ecebe',
set -g @catppuccin_sky       '#8fc9e6',
set -g @catppuccin_sapphire  '#94d1e5',
set -g @catppuccin_blue      '#9ccfe9',
set -g @catppuccin_lavender  '#c1d0f2',

set -g @catppuccin_text      '#c3c3c4',
set -g @catppuccin_subtext1  '#b2b2b3',
set -g @catppuccin_subtext0  '#a0a0c1',
set -g @catppuccin_overlay2  '#939394',
set -g @catppuccin_overlay1  '#757576',
set -g @catppuccin_overlay0  '#636364',
set -g @catppuccin_surface2  '#434344',
set -g @catppuccin_surface1  '#323233',
set -g @catppuccin_surface0  '#212122',
set -g @catppuccin_base      '#19191a',
set -g @catppuccin_mantle    '#141415',
set -g @catppuccin_crust     '#101011',
