# Prefix
unbind C-b
set -g prefix M-space
bind M-space send-prefix

# Config reloading
unbind r
bind r source-file $XDG_CONFIG_HOME/tmux/tmux.conf

# Pane splitting vertically
unbind '"'
bind s split-window -v

# Pane splitting horizontally
unbind %
bind v split-window -h

# Resize panes
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind o resize-pane -Z

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
