set -g status-position top

set -g status-style 'fg=#{@catppuccin_text},bg=#{@catppuccin_mantle}'

set -g status-left-length 200
set -g status-left ''

set -g status-right-length 200
set -g status-right ''

set -ga status-right '#[fg=#{@catppuccin_text},bg=#{@catppuccin_surface0}] #{session_path} '
set -ga status-right '#[fg=#{@catppuccin_base},bg=#{@catppuccin_sky}] Workdir '

set -ga status-right '#[bg=#{@catppuccin_mantle}] '

set -ga status-right '#[fg=#{@catppuccin_text},bg=#{@catppuccin_surface0}] #S '
set -ga status-right '#[fg=#{@catppuccin_base},bg=#{@catppuccin_lavender}] Session '

set -ga status-right '#[bg=#{@catppuccin_mantle}] '

set -ga status-right '#[fg=#{@catppuccin_base}]#{?client_prefix,#[bg=#{@catppuccin_green}] Unlocked,#[bg=#{@catppuccin_overlay2}] Locked} '

set -g window-status-current-format '#[fg=#{@catppuccin_base},bg=#{@catppuccin_blue}] #{window_index} #[fg=#{@catppuccin_text},bg=#{@catppuccin_surface0}] #{window_name} '
set -g window-status-format '#[fg=#{@catppuccin_subtext1},bg=#{@catppuccin_surface1}] #{window_index} #[fg=#{@catppuccin_subtext1},bg=#{@catppuccin_surface0}] #{window_name} '

