[bootstrap.packages]
"brew:mas" = "latest"
"brew:bash" = "latest"

# Casks
"brew-cask:cleanupbuddy" = "latest"
"brew-cask:clop" = "latest"
"brew-cask:crystalfetch" = "latest"
"brew-cask:cyberduck" = "latest"
"brew-cask:discord" = "latest"
"brew-cask:firefox@developer-edition" = "latest"
"brew-cask:font-jetbrains-mono" = "latest"
"brew-cask:font-symbols-only-nerd-font" = "latest"
"brew-cask:ghostty" = "latest"
"brew-cask:google-chrome" = "latest"
"brew-cask:helium-browser" = "latest"
"brew-cask:hex-fiend" = "latest"
"brew-cask:bruno" = "latest"
"brew-cask:iina" = "latest"
"brew-cask:keepingyouawake" = "latest"
"brew-cask:keka" = "latest"
"brew-cask:kekaexternalhelper" = "latest"
"brew-cask:mac-mouse-fix" = "latest"
"brew-cask:obs" = "latest"
"brew-cask:pearcleaner" = "latest"
"brew-cask:tablepro" = "latest"
"brew-cask:telegram" = "latest"
"brew-cask:tor-browser" = "latest"
"brew-cask:transmission" = "latest"

# Mac App Store
"mas:1632827132" = "latest"  # Camera Preview
"mas:1545870783" = "latest"  # Color Picker
"mas:1355679052" = "latest"  # Dropover
"mas:6444667067" = "latest"  # Hyperduck
"mas:1433648537" = "latest"  # Passepartout
"mas:1596706466" = "latest"  # Speediness
"mas:6477753172" = "latest"  # Square Sketch
"mas:1481853033" = "latest"  # Strongbox
"mas:1475387142" = "latest"  # Tailscale
"mas:899247664" = "latest"  # TestFlight
"mas:1295203466" = "latest"  # Windows App
"mas:6746388723" = "latest"  # wBlock

[dotfiles]
"~/.config/ghostty/config" = {}
"~/.config/ghostty/themes/catppina" = {}
