[app]
overall = { bg = "#19191a" }

[mgr]
cwd = { fg = "#7ecebe" }

find_keyword  = { fg = "#e9cc9c", italic = true }
find_position = { fg = "#e99cba", bg = "reset", italic = true }

marker_copied   = { fg = "#7fc7a4", bg = "#7fc7a4" }
marker_cut      = { fg = "#f88d8e", bg = "#f88d8e" }
marker_marked   = { fg = "#7ecebe", bg = "#7ecebe" }
marker_selected = { fg = "#9ccfe9", bg = "#9ccfe9" }

count_copied   = { fg = "#19191a", bg = "#7fc7a4" }
count_cut      = { fg = "#19191a", bg = "#f88d8e" }
count_selected = { fg = "#19191a", bg = "#9ccfe9" }

border_symbol = "│"
border_style  = { fg = "#757576" }

syntect_theme = "~/.config/yazi/Catppuccin-mocha.tmTheme"

[tabs]
active   = { fg = "#19191a", bg = "#c3c3c4", bold = true }
inactive = { fg = "#c3c3c4", bg = "#323233" }

[mode]
normal_main = { fg = "#19191a", bg = "#9ccfe9", bold = true }
normal_alt  = { fg = "#9ccfe9", bg = "#212122"}

select_main = { fg = "#19191a", bg = "#7fc7a4", bold = true }
select_alt  = { fg = "#7fc7a4", bg = "#212122"}

unset_main  = { fg = "#19191a", bg = "#ffafaf", bold = true }
unset_alt   = { fg = "#ffafaf", bg = "#212122"}

[indicator]
parent = { fg = "#19191a", bg = "#c3c3c4" }
current = { fg = "#19191a", bg = "#9ccfe9" }
preview = { fg = "#19191a", bg = "#c3c3c4" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#7fc7a4", bg = "#323233" }
progress_error  = { fg = "#e9cc9c", bg = "#f88d8e" }

perm_type  = { fg = "#9ccfe9" }
perm_read  = { fg = "#e9cc9c" }
perm_write = { fg = "#f88d8e" }
perm_exec  = { fg = "#7fc7a4" }
perm_sep   = { fg = "#757576" }

[input]
border   = { fg = "#9ccfe9" }
title    = {}
value    = {}
selected = { reversed = true }

[pick]
border   = { fg = "#9ccfe9" }
active   = { fg = "#e99cba" }
inactive = {}

[confirm]
border     = { fg = "#9ccfe9" }
title      = { fg = "#9ccfe9" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[cmp]
border = { fg = "#9ccfe9" }

[tasks]
border  = { fg = "#9ccfe9" }
title   = {}
hovered = { fg = "#e99cba", bold = true }

[which]
mask            = { bg = "#212122" }
cand            = { fg = "#7ecebe" }
rest            = { fg = "#939394" }
desc            = { fg = "#e99cba" }
separator       = "  "
separator_style = { fg = "#434344" }

[help]
on      = { fg = "#7ecebe" }
run     = { fg = "#e99cba" }
desc    = { fg = "#939394" }
hovered = { bg = "#434344", bold = true }
footer  = { fg = "#c3c3c4", bg = "#323233" }

[notify]
title_info  = { fg = "#7ecebe" }
title_warn  = { fg = "#e9cc9c" }
title_error = { fg = "#f88d8e" }

[filetype]
rules = [
	# Media
	{ mime = "image/*", fg = "#e9cc9c" },
	{ mime = "{audio,video}/*", fg = "#e99cba" },

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f88d8e" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#8fc9e6" },

	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#323233" },

	# Special file
	{ url = "*", is = "orphan", bg = "#f88d8e" },
	{ url = "*", is = "exec"  , fg = "#7fc7a4" },

	# Dummy file
	{ url = "*", is = "dummy", bg = "#f88d8e" },
	{ url = "*/", is = "dummy", bg = "#f88d8e" },

	# Fallback
	{ url = "*/", fg = "#9ccfe9" },
]

[spot]
border = { fg = "#9ccfe9" }
title  = { fg = "#9ccfe9" }
tbl_cell = { fg = "#9ccfe9", reversed = true }
tbl_col = { bold = true }

[icon]
dirs = [
	{ name = ".config", text = "", fg = "#9ccfe9" },
	{ name = ".git", text = "", fg = "#9ccfe9" },
	{ name = ".github", text = "", fg = "#9ccfe9" },
	{ name = ".npm", text = "", fg = "#9ccfe9" },
	{ name = "Desktop", text = "", fg = "#9ccfe9" },
	{ name = "Development", text = "", fg = "#9ccfe9" },
	{ name = "Documents", text = "", fg = "#9ccfe9" },
	{ name = "Downloads", text = "", fg = "#9ccfe9" },
	{ name = "Library", text = "", fg = "#9ccfe9" },
	{ name = "Movies", text = "", fg = "#9ccfe9" },
	{ name = "Music", text = "", fg = "#9ccfe9" },
	{ name = "Pictures", text = "", fg = "#9ccfe9" },
	{ name = "Public", text = "", fg = "#9ccfe9" },
	{ name = "Videos", text = "", fg = "#9ccfe9" },
]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "#c3c3c4" },
	{ if = "link", text = "", fg = "#a0a0a1" },
	{ if = "block", text = "", fg = "#e9cc9c" },
	{ if = "char", text = "", fg = "#e9cc9c" },
	{ if = "fifo", text = "", fg = "#e9cc9c" },
	{ if = "sock", text = "", fg = "#e9cc9c" },
	{ if = "sticky", text = "", fg = "#e9cc9c" },
	{ if = "dummy", text = "", fg = "#f88d8e" },

	# Fallback
	{ if = "dir", text = "", fg = "#9ccfe9" },
	{ if = "exec", text = "", fg = "#7fc7a4" },
	{ if = "!dir", text = "", fg = "#c3c3c4" },
]
