theme = "catppina"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
undercurl = true
end-of-line-diagnostics = "hint"
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "┃"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.lsp]
display-messages = true
auto-signature-help = false
display-inlay-hints = true
inlay-hints-length-limit = 36

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
"'" = "'"
'"' = '"'
'`' = '`'
'<' = '>'

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.space]
e = "file_picker"
E = [
  ":sh rm -f /tmp/unique-file-h21a434",
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file-h21a434",
  ":insert-output echo \"x1b[?1049h\" > /dev/tty",
  ":open %sh{cat /tmp/unique-file-h21a434}",
  ":redraw",
  ":set mouse false",
  ":set mouse true",
]
f = ":format"
F = "no_op"
i = ":toggle lsp.display-inlay-hints"
"?" = [
  ":write-all",
  ":insert-output scooter >/dev/tty",
  ":redraw",
  ":reload-all",
]
