theme = "catppina"

[editor]
bufferline = "always"
cursorline = true
line-number = "relative"
undercurl = true
end-of-line-diagnostics = "hint"
color-modes = true
true-color = true
rainbow-brackets = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.indent-guides]
render = true
character = "┃"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.lsp]
display-messages = true
auto-signature-help = false
display-inlay-hints = true
inlay-hints-length-limit = 36

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.auto-pairs]
'(' = ")"
'{' = "}"
'[' = "]"
"'" = "'"
'"' = '"'
'`' = "`"
'<' = ">"

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[keys.normal.space]
e = "file_picker"
f = ":format"
i = ":toggle lsp.display-inlay-hints"
F = "no_op"
E = "no_op"

[keys.select."+"]
c = ":pipe ut case camel -"
C = ":pipe ut case constant -"
l = ":pipe ut case lower -"
u = ":pipe ut case upper -"
h = ":pipe ut case header -"
s = ":pipe ut case snake -"
S = ":pipe ut case sentence -"
t = ":pipe ut case title -"
